sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "8"
install:
- npm install
script:
- npm test
after_script:
  - npm run coveralls
notifications:
  email:
    on_success: always
    on_failure: always
